import { mutation } from "./_generated/server";
import { v } from "convex/values";

export const seedAll = mutation({
  args: {
    footballStorageId: v.string(),
    cricketStorageId: v.string(),
    badmintonStorageId: v.string(),
    tennisStorageId: v.string(),
    trophyStorageId: v.string(),
  },
  handler: async (ctx, args) => {
    // 1. Clear existing database records for a fresh start
    const existingTurfs = await ctx.db.query("turfs").collect();
    for (const t of existingTurfs) {
      await ctx.db.delete(t._id);
    }
    const existingTournaments = await ctx.db.query("tournaments").collect();
    for (const t of existingTournaments) {
      await ctx.db.delete(t._id);
    }
    const existingTeams = await ctx.db.query("tournament_teams").collect();
    for (const t of existingTeams) {
      await ctx.db.delete(t._id);
    }
    const existingParticipants = await ctx.db.query("tournament_participants").collect();
    for (const p of existingParticipants) {
      await ctx.db.delete(p._id);
    }

    // 2. Fetch public URLs from Convex Storage IDs
    const footballUrl = (await ctx.storage.getUrl(args.footballStorageId)) || "";
    const cricketUrl = (await ctx.storage.getUrl(args.cricketStorageId)) || "";
    const badmintonUrl = (await ctx.storage.getUrl(args.badmintonStorageId)) || "";
    const tennisUrl = (await ctx.storage.getUrl(args.tennisStorageId)) || "";
    const trophyUrl = (await ctx.storage.getUrl(args.trophyStorageId)) || "";

    // 3. Find or seed a default owner user to own these turfs
    let owner = await ctx.db
      .query("users")
      .withIndex("by_email", (q) => q.eq("email", "owner@turfzo.com"))
      .unique();

    if (!owner) {
      const ownerId = await ctx.db.insert("users", {
        email: "owner@turfzo.com",
        full_name: "Default Venue Owner",
        display_name: "Venue Owner",
        role: "owner",
        is_email_verified: true,
        is_phone_verified: true,
        is_approved: true,
        notifications_enabled: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      });
      owner = await ctx.db.get(ownerId);
    }
    const ownerId = owner!._id;

    // 4. Seed 10 real turfs
    const turfData = [
      {
        name: "Mumbai Football Arena",
        description: "Professional grade indoor football turf with FIFA-approved grass. Perfect for 7v7 matches.",
        address: "Andheri Sports Complex, Link Road, Andheri West",
        city: "Mumbai",
        state: "Maharashtra",
        zip_code: "400053",
        price_per_hour: 1500,
        image_url: footballUrl,
        image_gallery: [footballUrl],
        is_available: true,
        sport_type: "Football",
        amenities: ["Flood Lights", "Free Parking", "Changing Room", "Drinking Water", "First Aid"],
        rating: 4.8,
        review_count: 145,
        tier: "premium",
        format: "7v7",
        location_name: "Andheri West",
        latitude: 19.129,
        longitude: 72.833,
        operating_hours: { open: "06:00", close: "23:00" },
        max_players: 14,
        has_floodlights: true,
        has_free_parking: true,
        has_changing_room: true,
        has_drinking_water: true,
        has_first_aid: true,
        is_indoor: true,
        ground_count: 2,
        status: "active" as const,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Koramangala Turf Club",
        description: "Premium 5-a-side rooftop football turf with gorgeous stadium lights and spectator seating.",
        address: "80 Feet Road, 4th Block, Koramangala",
        city: "Bangalore",
        state: "Karnataka",
        zip_code: "560034",
        price_per_hour: 1200,
        image_url: footballUrl,
        image_gallery: [footballUrl],
        is_available: true,
        sport_type: "Football",
        amenities: ["Flood Lights", "Changing Room", "Drinking Water", "First Aid"],
        rating: 4.6,
        review_count: 98,
        tier: "standard",
        format: "5v5",
        location_name: "Koramangala",
        latitude: 12.935,
        longitude: 77.624,
        operating_hours: { open: "06:00", close: "22:00" },
        max_players: 10,
        has_floodlights: true,
        has_free_parking: false,
        has_changing_room: true,
        has_drinking_water: true,
        has_first_aid: true,
        is_indoor: false,
        ground_count: 1,
        status: "active" as const,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Gachibowli Sports Hub",
        description: "A colossal 11v11 football field that can also be partitioned for smaller training sessions.",
        address: "Near Gachibowli Stadium, ISB Road",
        city: "Hyderabad",
        state: "Telangana",
        zip_code: "500032",
        price_per_hour: 2500,
        image_url: footballUrl,
        image_gallery: [footballUrl],
        is_available: true,
        sport_type: "Football",
        amenities: ["Flood Lights", "Free Parking", "Changing Room", "Drinking Water", "First Aid", "Cafeteria"],
        rating: 4.9,
        review_count: 210,
        tier: "premium",
        format: "11v11",
        location_name: "Gachibowli",
        latitude: 17.448,
        longitude: 78.348,
        operating_hours: { open: "05:00", close: "23:00" },
        max_players: 22,
        has_floodlights: true,
        has_free_parking: true,
        has_changing_room: true,
        has_drinking_water: true,
        has_first_aid: true,
        is_indoor: false,
        ground_count: 1,
        status: "active" as const,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Delhi Cricket Academy & Nets",
        description: "Lush green outdoor cricket nets with high-quality clay pitch and professional balling machines.",
        address: "Saket Sports Complex, Marg 3, Saket",
        city: "Delhi",
        state: "Delhi",
        zip_code: "110017",
        price_per_hour: 800,
        image_url: cricketUrl,
        image_gallery: [cricketUrl],
        is_available: true,
        sport_type: "Cricket",
        amenities: ["Free Parking", "Drinking Water", "First Aid", "Bowling Machine"],
        rating: 4.7,
        review_count: 67,
        tier: "standard",
        format: "Net Practice",
        location_name: "Saket",
        latitude: 28.524,
        longitude: 77.206,
        operating_hours: { open: "06:00", close: "20:00" },
        max_players: 6,
        has_floodlights: false,
        has_free_parking: true,
        has_changing_room: false,
        has_drinking_water: true,
        has_first_aid: true,
        is_indoor: false,
        ground_count: 4,
        status: "active" as const,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Whitefield Cricket Hub",
        description: "State-of-the-art indoor box cricket arena with professional turf and protective nets. Floodlights included.",
        address: "ITPL Main Road, Mahadevapura, Whitefield",
        city: "Bangalore",
        state: "Karnataka",
        zip_code: "560066",
        price_per_hour: 1000,
        image_url: cricketUrl,
        image_gallery: [cricketUrl],
        is_available: true,
        sport_type: "Cricket",
        amenities: ["Flood Lights", "Free Parking", "Changing Room", "Drinking Water", "First Aid"],
        rating: 4.5,
        review_count: 89,
        tier: "standard",
        format: "Box Cricket",
        location_name: "Whitefield",
        latitude: 12.969,
        longitude: 77.749,
        operating_hours: { open: "06:00", close: "23:00" },
        max_players: 12,
        has_floodlights: true,
        has_free_parking: true,
        has_changing_room: true,
        has_drinking_water: true,
        has_first_aid: true,
        is_indoor: true,
        ground_count: 2,
        status: "active" as const,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Powai Box Cricket Ground",
        description: "Outdoor box cricket ground with seamless artificial grass, high boundary nets, and superb night lights.",
        address: "Hiranandani Gardens, Powai",
        city: "Mumbai",
        state: "Maharashtra",
        zip_code: "400076",
        price_per_hour: 1200,
        image_url: cricketUrl,
        image_gallery: [cricketUrl],
        is_available: true,
        sport_type: "Cricket",
        amenities: ["Flood Lights", "Drinking Water", "First Aid"],
        rating: 4.6,
        review_count: 112,
        tier: "standard",
        format: "Box Cricket",
        location_name: "Powai",
        latitude: 19.117,
        longitude: 72.906,
        operating_hours: { open: "06:00", close: "24:00" },
        max_players: 14,
        has_floodlights: true,
        has_free_parking: false,
        has_changing_room: false,
        has_drinking_water: true,
        has_first_aid: true,
        is_indoor: false,
        ground_count: 1,
        status: "active" as const,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Indiranagar Badminton Arena",
        description: "Premium facility featuring 4 professional wooden badminton courts with non-slip coating and clear sightlines.",
        address: "100 Feet Road, Indiranagar",
        city: "Bangalore",
        state: "Karnataka",
        zip_code: "560038",
        price_per_hour: 500,
        image_url: badmintonUrl,
        image_gallery: [badmintonUrl],
        is_available: true,
        sport_type: "Badminton",
        amenities: ["Free Parking", "Changing Room", "Drinking Water", "First Aid", "Shower"],
        rating: 4.8,
        review_count: 220,
        tier: "premium",
        format: "Wooden Court",
        location_name: "Indiranagar",
        latitude: 12.971,
        longitude: 77.641,
        operating_hours: { open: "05:00", close: "23:00" },
        max_players: 4,
        has_floodlights: true,
        has_free_parking: true,
        has_changing_room: true,
        has_drinking_water: true,
        has_first_aid: true,
        is_indoor: true,
        ground_count: 4,
        status: "active" as const,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Jubilee Hills Badminton Palace",
        description: "6 BWF-approved synthetic mats with custom non-glare LED sports lighting. Racket rentals available.",
        address: "Road No 36, Jubilee Hills",
        city: "Hyderabad",
        state: "Telangana",
        zip_code: "500033",
        price_per_hour: 450,
        image_url: badmintonUrl,
        image_gallery: [badmintonUrl],
        is_available: true,
        sport_type: "Badminton",
        amenities: ["Free Parking", "Changing Room", "Drinking Water", "First Aid"],
        rating: 4.7,
        review_count: 178,
        tier: "premium",
        format: "Synthetic Court",
        location_name: "Jubilee Hills",
        latitude: 17.432,
        longitude: 78.407,
        operating_hours: { open: "05:00", close: "22:00" },
        max_players: 4,
        has_floodlights: true,
        has_free_parking: true,
        has_changing_room: true,
        has_drinking_water: true,
        has_first_aid: true,
        is_indoor: true,
        ground_count: 6,
        status: "active" as const,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Gachibowli Clay Court Masters",
        description: "Beautiful red clay tennis courts styled after Roland Garros. Maintained daily for perfect bounce.",
        address: "Telecom Nagar, Gachibowli",
        city: "Hyderabad",
        state: "Telangana",
        zip_code: "500032",
        price_per_hour: 800,
        image_url: tennisUrl,
        image_gallery: [tennisUrl],
        is_available: true,
        sport_type: "Tennis",
        amenities: ["Free Parking", "Changing Room", "Drinking Water", "First Aid", "Cafeteria"],
        rating: 4.9,
        review_count: 54,
        tier: "premium",
        format: "Clay Court",
        location_name: "Gachibowli",
        latitude: 17.44,
        longitude: 78.35,
        operating_hours: { open: "06:00", close: "21:00" },
        max_players: 4,
        has_floodlights: true,
        has_free_parking: true,
        has_changing_room: true,
        has_drinking_water: true,
        has_first_aid: true,
        is_indoor: false,
        ground_count: 2,
        status: "active" as const,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Connaught Place Tennis Arena",
        description: "Plexipave hard courts in the center of New Delhi. Ideal for singles or doubles competitive matches.",
        address: "Outer Circle, Connaught Place",
        city: "Delhi",
        state: "Delhi",
        zip_code: "110001",
        price_per_hour: 900,
        image_url: tennisUrl,
        image_gallery: [tennisUrl],
        is_available: true,
        sport_type: "Tennis",
        amenities: ["Flood Lights", "Drinking Water", "First Aid"],
        rating: 4.6,
        review_count: 82,
        tier: "standard",
        format: "Hard Court",
        location_name: "Connaught Place",
        latitude: 28.63,
        longitude: 77.22,
        operating_hours: { open: "06:00", close: "22:00" },
        max_players: 4,
        has_floodlights: true,
        has_free_parking: false,
        has_changing_room: false,
        has_drinking_water: true,
        has_first_aid: true,
        is_indoor: false,
        ground_count: 2,
        status: "active" as const,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ];

    const seededTurfIds: string[] = [];
    for (const turf of turfData) {
      const id = await ctx.db.insert("turfs", {
        ...turf,
        user_id: ownerId,
      });
      seededTurfIds.push(id);
    }

    // 5. Seed 10 tournaments corresponding to the turfs
    const tournamentData = [
      {
        name: "Mumbai Football Championship",
        description: "The ultimate 7v7 football tournament for amateur teams in Mumbai. Cash prize for Winners & Runners up.",
        sport_type: "Football",
        tournament_type: "7v7 Knockout",
        entry_fee: 2000,
        prize_pool: 50000,
        max_participants: 16,
        min_team_size: 7,
        max_team_size: 10,
        registration_deadline: "2026-07-15",
        start_date: "2026-07-20",
        end_date: "2026-07-22",
        bracket_type: "single_elimination",
        auto_generate_bracket: true,
        status: "open",
        rules: "Standard FIFA 7v7 rules. 20-minute halves. Rolling substitutions.",
        image_url: trophyUrl,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Koramangala Futsal League",
        description: "Fast-paced 5v5 indoor football tournament under the rooftop lights of Bangalore.",
        sport_type: "Football",
        tournament_type: "5v5 League + Knockout",
        entry_fee: 1500,
        prize_pool: 30000,
        max_participants: 12,
        min_team_size: 5,
        max_team_size: 8,
        registration_deadline: "2026-07-10",
        start_date: "2026-07-14",
        end_date: "2026-07-16",
        bracket_type: "league_groups",
        auto_generate_bracket: true,
        status: "open",
        rules: "Standard Futsal rules. 15-minute halves. Non-marking shoes mandatory.",
        image_url: footballUrl,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Gachibowli Mega Soccer Cup",
        description: "Grand 11-a-side football cup for corporate and club teams in Hyderabad. Professional refs.",
        sport_type: "Football",
        tournament_type: "11v11 Knockout",
        entry_fee: 3000,
        prize_pool: 75000,
        max_participants: 16,
        min_team_size: 11,
        max_team_size: 15,
        registration_deadline: "2026-07-22",
        start_date: "2026-07-26",
        end_date: "2026-07-30",
        bracket_type: "single_elimination",
        auto_generate_bracket: true,
        status: "open",
        rules: "Full size pitch. Offside rules apply. 30-minute halves.",
        image_url: trophyUrl,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Delhi Box Cricket Carnival",
        description: "Thrilling box cricket cup in Delhi. Short format, huge excitement, instant cash prizes.",
        sport_type: "Cricket",
        tournament_type: "Box Cricket",
        entry_fee: 1000,
        prize_pool: 20000,
        max_participants: 24,
        min_team_size: 6,
        max_team_size: 8,
        registration_deadline: "2026-07-05",
        start_date: "2026-07-08",
        end_date: "2026-07-10",
        bracket_type: "single_elimination",
        auto_generate_bracket: true,
        status: "open",
        rules: "6 overs per innings. Underarm bowling only. Batsman out on direct hitting the roof.",
        image_url: cricketUrl,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Whitefield Cricket Bash",
        description: "Corporate box cricket league in Bangalore. Great networking, competitive cricket.",
        sport_type: "Cricket",
        tournament_type: "Box Cricket League",
        entry_fee: 1200,
        prize_pool: 25000,
        max_participants: 16,
        min_team_size: 6,
        max_team_size: 8,
        registration_deadline: "2026-07-18",
        start_date: "2026-07-22",
        end_date: "2026-07-25",
        bracket_type: "league_groups",
        auto_generate_bracket: true,
        status: "open",
        rules: "Tennis ball cricket. 8 overs per side. Max 2 overs per bowler.",
        image_url: trophyUrl,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Powai Super Sixes",
        description: "High stakes box cricket tournament in Hiranandani Powai. Bring your best hard-hitters.",
        sport_type: "Cricket",
        tournament_type: "Box Cricket",
        entry_fee: 1500,
        prize_pool: 35000,
        max_participants: 16,
        min_team_size: 6,
        max_team_size: 8,
        registration_deadline: "2026-07-02",
        start_date: "2026-07-05",
        end_date: "2026-07-06",
        bracket_type: "single_elimination",
        auto_generate_bracket: true,
        status: "open",
        rules: "Standard tennis box cricket rules. Golden ball in final over.",
        image_url: cricketUrl,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Indiranagar Badminton Open",
        description: "Singles and Doubles open tournament on the premium wooden courts of Indiranagar.",
        sport_type: "Badminton",
        tournament_type: "Singles & Doubles",
        entry_fee: 500,
        prize_pool: 10000,
        max_participants: 32,
        min_team_size: 1,
        max_team_size: 2,
        registration_deadline: "2026-07-12",
        start_date: "2026-07-16",
        end_date: "2026-07-18",
        bracket_type: "single_elimination",
        auto_generate_bracket: true,
        status: "open",
        rules: "Best of 3 games, 21 points each. Yonex Mavis 350 shuttles will be provided.",
        image_url: trophyUrl,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Jubilee Hills Shuttle Clash",
        description: "Amateur badminton championship in Hyderabad. Separate categories for Men, Women & Mixed.",
        sport_type: "Badminton",
        tournament_type: "Doubles Knockout",
        entry_fee: 400,
        prize_pool: 8000,
        max_participants: 32,
        min_team_size: 2,
        max_team_size: 2,
        registration_deadline: "2026-07-28",
        start_date: "2026-08-01",
        end_date: "2026-08-03",
        bracket_type: "single_elimination",
        auto_generate_bracket: true,
        status: "open",
        rules: "BWF tournament rules apply. Non-marking shoes are mandatory on synthetic mats.",
        image_url: badmintonUrl,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Hyderabad Clay Court Masters",
        description: "Clay court singles tournament. Experience playing like the pros on a top-tier clay surface.",
        sport_type: "Tennis",
        tournament_type: "Singles Knockout",
        entry_fee: 800,
        prize_pool: 15000,
        max_participants: 16,
        min_team_size: 1,
        max_team_size: 1,
        registration_deadline: "2026-07-18",
        start_date: "2026-07-21",
        end_date: "2026-07-24",
        bracket_type: "single_elimination",
        auto_generate_bracket: true,
        status: "open",
        rules: "Standard tennis tiebreaker format. Best of 3 sets.",
        image_url: trophyUrl,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        name: "Delhi Tennis Grand Slam",
        description: "Amateur tennis doubles tournament in the heart of Delhi. Hard court surface.",
        sport_type: "Tennis",
        tournament_type: "Doubles Knockout",
        entry_fee: 1000,
        prize_pool: 20000,
        max_participants: 16,
        min_team_size: 2,
        max_team_size: 2,
        registration_deadline: "2026-07-10",
        start_date: "2026-07-12",
        end_date: "2026-07-15",
        bracket_type: "single_elimination",
        auto_generate_bracket: true,
        status: "open",
        rules: "Wilson US Open balls will be used. Pro-set rules for early rounds, full sets for semi/finals.",
        image_url: tennisUrl,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ];

    // Associate tournaments with the seeded turfs respectively
    for (let i = 0; i < tournamentData.length; i++) {
      const t = tournamentData[i];
      const associatedTurfId = seededTurfIds[i]; // map 1-to-1
      await ctx.db.insert("tournaments", {
        ...t,
        organizer_id: ownerId,
        turf_id: associatedTurfId,
      });
    }

    return {
      turfsSeeded: seededTurfIds.length,
      tournamentsSeeded: tournamentData.length,
      ownerEmail: "owner@turfzo.com",
    };
  },
});
