import { mutation } from "./_generated/server";

const sampleTurfs = [
  {
    name: "Olympic Arena Football Turf",
    description: "Professional grade football turf with high-quality grass and floodlights. 7v7 and 5v5 formats available.",
    address: "Andheri Sports Complex, JP Road, Andheri West",
    city: "Mumbai",
    state: "Maharashtra",
    zip_code: "400053",
    price_per_hour: 1200,
    image_url: "/stadium_turf_bg.png",
    is_available: true,
    sport_type: "Football",
    amenities: ["Flood Lights", "Parking", "Changing Room", "Drinking Water", "First Aid"],
    rating: 4.8,
    review_count: 230,
    tier: "premium",
    format: "7v7",
    location_name: "Andheri West",
    latitude: 19.129,
    longitude: 72.833,
    operating_hours: { open: "06:00", close: "23:00" },
    max_players: 14,
    has_floodlights: true,
    has_free_parking: true,
    has_changing_room: true,
    has_drinking_water: true,
    has_first_aid: true,
    is_indoor: false,
  },
  {
    name: "Green Valley Turf",
    description: "Premium natural grass football turf in the heart of Koramangala.",
    address: "5th Block, Koramangala",
    city: "Bangalore",
    state: "Karnataka",
    zip_code: "560095",
    price_per_hour: 1000,
    image_url: "/stadium_turf_bg.png",
    is_available: true,
    sport_type: "Football",
    amenities: ["Flood Lights", "Parking", "Cafeteria"],
    rating: 4.7,
    review_count: 180,
    tier: "standard",
    format: "5v5",
    location_name: "Koramangala",
    latitude: 12.9352,
    longitude: 77.6245,
    operating_hours: { open: "06:00", close: "22:00" },
    max_players: 10,
    has_floodlights: true,
    has_free_parking: true,
    has_changing_room: true,
    has_drinking_water: true,
    has_first_aid: false,
    is_indoor: false,
  },
  {
    name: "Bangalore Football Arena",
    description: "FIFA-standard football turf with advanced drainage system.",
    address: "100 Feet Road, Indiranagar",
    city: "Bangalore",
    state: "Karnataka",
    zip_code: "560038",
    price_per_hour: 1500,
    image_url: "/stadium_turf_bg.png",
    is_available: true,
    sport_type: "Football",
    amenities: ["Flood Lights", "Changing Room", "Parking", "Drinking Water", "First Aid", "Cafeteria"],
    rating: 4.9,
    review_count: 320,
    tier: "premium",
    format: "11v11",
    location_name: "Indiranagar",
    latitude: 12.9719,
    longitude: 77.6412,
    operating_hours: { open: "05:00", close: "23:00" },
    max_players: 22,
    has_floodlights: true,
    has_free_parking: true,
    has_changing_room: true,
    has_drinking_water: true,
    has_first_aid: true,
    is_indoor: false,
  },
  {
    name: "Playo Turf HSR",
    description: "Modern 7-a-side football turf in HSR Layout with quality floodlights.",
    address: "Sector 2, HSR Layout",
    city: "Bangalore",
    state: "Karnataka",
    zip_code: "560102",
    price_per_hour: 1100,
    image_url: "/stadium_turf_bg.png",
    is_available: true,
    sport_type: "Football",
    amenities: ["Flood Lights", "Parking", "Changing Room"],
    rating: 4.6,
    review_count: 145,
    tier: "standard",
    format: "7v7",
    location_name: "HSR Layout",
    latitude: 12.9116,
    longitude: 77.6473,
    operating_hours: { open: "06:00", close: "23:00" },
    max_players: 14,
    has_floodlights: true,
    has_free_parking: true,
    has_changing_room: true,
    has_drinking_water: true,
    has_first_aid: true,
    is_indoor: false,
  },
  {
    name: "Whitefield Sports Arena",
    description: "Spacious football and cricket turf in Whitefield.",
    address: "Whitefield Main Road",
    city: "Bangalore",
    state: "Karnataka",
    zip_code: "560066",
    price_per_hour: 900,
    image_url: "/stadium_turf_bg.png",
    is_available: true,
    sport_type: "Multipurpose",
    amenities: ["Flood Lights", "Parking", "Drinking Water"],
    rating: 4.4,
    review_count: 98,
    tier: "standard",
    format: "7v7",
    location_name: "Whitefield",
    latitude: 12.9698,
    longitude: 77.7499,
    operating_hours: { open: "06:00", close: "22:00" },
    max_players: 14,
    has_floodlights: true,
    has_free_parking: true,
    has_changing_room: false,
    has_drinking_water: true,
    has_first_aid: true,
    is_indoor: false,
  },
  {
    name: "Indiranagar Cricket Club",
    description: "Box cricket turf perfect for 6-a-side games.",
    address: "12th Main, Indiranagar",
    city: "Bangalore",
    state: "Karnataka",
    zip_code: "560038",
    price_per_hour: 1300,
    image_url: "/stadium_turf_bg.png",
    is_available: true,
    sport_type: "Cricket",
    amenities: ["Flood Lights", "Parking", "Changing Room", "Cafeteria"],
    rating: 4.7,
    review_count: 167,
    tier: "premium",
    format: "6v6",
    location_name: "Indiranagar",
    latitude: 12.9784,
    longitude: 77.6408,
    operating_hours: { open: "06:00", close: "23:00" },
    max_players: 12,
    has_floodlights: true,
    has_free_parking: true,
    has_changing_room: true,
    has_drinking_water: true,
    has_first_aid: true,
    is_indoor: false,
  },
  {
    name: "Bandra Turf Park",
    description: "Compact football turf in Bandra with great vibes.",
    address: "Bandra West, Near Linking Road",
    city: "Mumbai",
    state: "Maharashtra",
    zip_code: "400050",
    price_per_hour: 1300,
    image_url: "/stadium_turf_bg.png",
    is_available: true,
    sport_type: "Football",
    amenities: ["Flood Lights", "Parking", "Changing Room"],
    rating: 4.5,
    review_count: 89,
    tier: "standard",
    format: "5v5",
    location_name: "Bandra West",
    latitude: 19.0596,
    longitude: 72.8295,
    operating_hours: { open: "07:00", close: "23:00" },
    max_players: 10,
    has_floodlights: true,
    has_free_parking: false,
    has_changing_room: true,
    has_drinking_water: true,
    has_first_aid: true,
    is_indoor: false,
  },
  {
    name: "Powai Sports Hub",
    description: "Indoor badminton and football courts, perfect for monsoons.",
    address: "Hiranandani Gardens, Powai",
    city: "Mumbai",
    state: "Maharashtra",
    zip_code: "400076",
    price_per_hour: 1400,
    image_url: "/stadium_turf_bg.png",
    is_available: true,
    sport_type: "Multipurpose",
    amenities: ["Flood Lights", "Parking", "Changing Room", "Drinking Water", "Cafeteria"],
    rating: 4.8,
    review_count: 245,
    tier: "premium",
    format: "5v5",
    location_name: "Powai",
    latitude: 19.1170,
    longitude: 72.9060,
    operating_hours: { open: "06:00", close: "23:00" },
    max_players: 10,
    has_floodlights: true,
    has_free_parking: true,
    has_changing_room: true,
    has_drinking_water: true,
    has_first_aid: true,
    is_indoor: true,
  },
  {
    name: "Saket Sports Complex",
    description: "Premium football turf in the heart of South Delhi.",
    address: "Saket District Centre",
    city: "Delhi",
    state: "Delhi",
    zip_code: "110017",
    price_per_hour: 1600,
    image_url: "/stadium_turf_bg.png",
    is_available: true,
    sport_type: "Football",
    amenities: ["Flood Lights", "Parking", "Changing Room", "Drinking Water"],
    rating: 4.6,
    review_count: 198,
    tier: "premium",
    format: "7v7",
    location_name: "Saket",
    latitude: 28.5244,
    longitude: 77.2066,
    operating_hours: { open: "06:00", close: "22:00" },
    max_players: 14,
    has_floodlights: true,
    has_free_parking: true,
    has_changing_room: true,
    has_drinking_water: true,
    has_first_aid: true,
    is_indoor: false,
  },
  {
    name: "Gachibowli Turf",
    description: "Hyderabad's premier 7v7 football turf.",
    address: "Gachibowli Stadium Road",
    city: "Hyderabad",
    state: "Telangana",
    zip_code: "500032",
    price_per_hour: 1100,
    image_url: "/stadium_turf_bg.png",
    is_available: true,
    sport_type: "Football",
    amenities: ["Flood Lights", "Parking", "Changing Room"],
    rating: 4.5,
    review_count: 156,
    tier: "standard",
    format: "7v7",
    location_name: "Gachibowli",
    latitude: 17.4401,
    longitude: 78.3489,
    operating_hours: { open: "06:00", close: "23:00" },
    max_players: 14,
    has_floodlights: true,
    has_free_parking: true,
    has_changing_room: true,
    has_drinking_water: true,
    has_first_aid: true,
    is_indoor: false,
  },
  {
    name: "Koregaon Park Arena",
    description: "Upscale sports venue in Pune's premium neighborhood.",
    address: "Koregaon Park, North Main Road",
    city: "Pune",
    state: "Maharashtra",
    zip_code: "411001",
    price_per_hour: 1250,
    image_url: "/stadium_turf_bg.png",
    is_available: true,
    sport_type: "Football",
    amenities: ["Flood Lights", "Parking", "Cafeteria", "Drinking Water"],
    rating: 4.7,
    review_count: 134,
    tier: "premium",
    format: "5v5",
    location_name: "Koregaon Park",
    latitude: 18.5362,
    longitude: 73.8939,
    operating_hours: { open: "06:00", close: "22:00" },
    max_players: 10,
    has_floodlights: true,
    has_free_parking: true,
    has_changing_room: true,
    has_drinking_water: true,
    has_first_aid: true,
    is_indoor: false,
  },
  {
    name: "T Nagar Sports Hub",
    description: "Chennai's favorite multi-sport venue with cricket and football.",
    address: "T Nagar, Panagal Park",
    city: "Chennai",
    state: "Tamil Nadu",
    zip_code: "600017",
    price_per_hour: 950,
    image_url: "/stadium_turf_bg.png",
    is_available: true,
    sport_type: "Multipurpose",
    amenities: ["Flood Lights", "Parking", "Drinking Water"],
    rating: 4.4,
    review_count: 87,
    tier: "standard",
    format: "6v6",
    location_name: "T Nagar",
    latitude: 13.0418,
    longitude: 80.2341,
    operating_hours: { open: "06:00", close: "22:00" },
    max_players: 12,
    has_floodlights: true,
    has_free_parking: true,
    has_changing_room: true,
    has_drinking_water: true,
    has_first_aid: false,
    is_indoor: false,
  },
];

const sampleTournaments = [
  {
    title: "Turfzo Summer Football Cup",
    sport: "Football",
    format: "7v7 Knockout",
    description: "Annual knockout football tournament hosted at the best HSR turfs. Cash prizes for top 3 teams.",
    start_date: "2026-06-12",
    end_date: "2026-06-15",
    venue: "Playo Turf, HSR Layout",
    city: "Bangalore",
    entry_fee: 1500,
    prize_pool: "₹50,000 + Trophy",
    max_teams: 16,
    registered_teams: 14,
    status: "open" as const,
    image_url: "/stadium_turf_bg.png",
    created_at: new Date().toISOString(),
  },
  {
    title: "Monsoon Cricket Championship",
    sport: "Cricket",
    format: "6v6 Box Cricket",
    description: "Box cricket tournament with 6 players per side. Quick matches, big fun.",
    start_date: "2026-06-20",
    end_date: "2026-06-22",
    venue: "Indiranagar Cricket Club",
    city: "Bangalore",
    entry_fee: 1200,
    prize_pool: "₹35,000 + Medals",
    max_teams: 12,
    registered_teams: 8,
    status: "open" as const,
    image_url: "/stadium_turf_bg.png",
    created_at: new Date().toISOString(),
  },
  {
    title: "Corporate Badminton Clash",
    sport: "Badminton",
    format: "Doubles Tournament",
    description: "Corporate doubles badminton tournament. Network and compete with professionals.",
    start_date: "2026-06-28",
    end_date: "2026-06-29",
    venue: "Golden Sports Arena",
    city: "Bangalore",
    entry_fee: 500,
    prize_pool: "₹15,000 Cash Prize",
    max_teams: 24,
    registered_teams: 18,
    status: "open" as const,
    image_url: "/stadium_turf_bg.png",
    created_at: new Date().toISOString(),
  },
  {
    title: "Mumbai Monsoon Football League",
    sport: "Football",
    format: "5v5 League",
    description: "Indoor football league across Mumbai's best indoor venues.",
    start_date: "2026-07-05",
    end_date: "2026-07-20",
    venue: "Powai Sports Hub",
    city: "Mumbai",
    entry_fee: 2000,
    prize_pool: "₹1,00,000 Prize Pool",
    max_teams: 20,
    registered_teams: 5,
    status: "open" as const,
    image_url: "/stadium_turf_bg.png",
    created_at: new Date().toISOString(),
  },
  {
    title: "Delhi Badminton Open",
    sport: "Badminton",
    format: "Singles Knockout",
    description: "Open singles badminton knockout tournament.",
    start_date: "2026-07-10",
    end_date: "2026-07-12",
    venue: "Saket Sports Complex",
    city: "Delhi",
    entry_fee: 800,
    prize_pool: "₹25,000 Cash",
    max_teams: 32,
    registered_teams: 12,
    status: "open" as const,
    image_url: "/stadium_turf_bg.png",
    created_at: new Date().toISOString(),
  },
];

export const seedTurfs = mutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query("turfs").first();
    if (existing) {
      return { inserted: 0, message: "Turfs already exist. Skipping." };
    }
    let inserted = 0;
    for (const turf of sampleTurfs) {
      await ctx.db.insert("turfs", turf);
      inserted++;
    }
    return { inserted, message: `Inserted ${inserted} turfs.` };
  },
});

export const seedTournaments = mutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query("tournaments").first();
    if (existing) {
      return { inserted: 0, message: "Tournaments already exist. Skipping." };
    }
    let inserted = 0;
    for (const t of sampleTournaments) {
      await ctx.db.insert("tournaments", t);
      inserted++;
    }
    return { inserted, message: `Inserted ${inserted} tournaments.` };
  },
});

export const seedAll = mutation({
  args: {},
  handler: async (ctx) => {
    const turfResult = { inserted: 0 };
    const tResult = { inserted: 0 };

    const existingTurfs = await ctx.db.query("turfs").first();
    if (!existingTurfs) {
      for (const turf of sampleTurfs) {
        await ctx.db.insert("turfs", turf);
        turfResult.inserted++;
      }
    }

    const existingTournaments = await ctx.db.query("tournaments").first();
    if (!existingTournaments) {
      for (const t of sampleTournaments) {
        await ctx.db.insert("tournaments", t);
        tResult.inserted++;
      }
    }

    return {
      turfs: turfResult.inserted,
      tournaments: tResult.inserted,
    };
  },
});
